import raw from "@/../docs/qa-evidence.json";

/**
 * The verification record the quality page reads (指示書 §10, 受け入れ基準 U08).
 *
 * Generated by `npm run qa:evidence`, committed, and imported at build time —
 * so the page shows a real run rather than a claim, and the commit it belongs
 * to is stated next to it.
 *
 * The file is committed, which means it can fall behind the code. That is
 * handled by saying so: `ageInDays` and `dirty` travel to the screen instead
 * of being smoothed away. A record whose age is invisible is a record that
 * quietly becomes a lie.
 */

export const SUITE_STATUSES = [
  "passed",
  "failed",
  "measured",
  "not_run",
] as const;
export type SuiteStatus = (typeof SUITE_STATUSES)[number];

export type QaSuite = {
  id: string;
  label: string;
  scope: "automated";
  status: SuiteStatus;
  detail?: string;
  reason?: string;
  checkedAt: string | null;
  total: number | null;
  failed: number | null;
  skipped?: number;
};

export type QaEvidence = {
  schema: number;
  commit: string;
  commitShort: string;
  committedAt: string;
  generatedAt: string;
  dirty: boolean;
  suites: QaSuite[];
};

/** Reports older than this are labelled stale on the page. */
export const STALE_AFTER_DAYS = 30;

export const evidence = raw as QaEvidence;

export const STATUS_LABELS: Record<SuiteStatus, string> = {
  passed: "PASS",
  failed: "FAIL",
  measured: "計測値",
  not_run: "未実施",
};

export function ageInDays(from: string, now = Date.now()): number | null {
  const at = Date.parse(from);
  if (!Number.isFinite(at)) return null;
  return Math.floor((now - at) / 86_400_000);
}

/**
 * The one-line summary above the table.
 *
 * Counts `not_run` separately and never folds it into a pass rate: a suite
 * nobody ran is not a suite that succeeded (指示書 O10).
 */
export function summarise(data: QaEvidence = evidence, now = Date.now()) {
  const counted = data.suites;
  const passed = counted.filter((s) => s.status === "passed").length;
  const failed = counted.filter((s) => s.status === "failed").length;
  const notRun = counted.filter((s) => s.status === "not_run").length;
  const measured = counted.filter((s) => s.status === "measured").length;
  const age = ageInDays(data.generatedAt, now);
  return {
    passed,
    failed,
    notRun,
    measured,
    total: counted.length,
    ageInDays: age,
    stale: age !== null && age > STALE_AFTER_DAYS,
    /** True when the record was taken with uncommitted changes present. */
    dirty: data.dirty,
    /** Total tests across suites that report a count. */
    tests: counted.reduce((sum, s) => sum + (s.total ?? 0), 0),
  };
}

export const formatStamp = (iso: string | null): string => {
  if (!iso) return "—";
  const at = Date.parse(iso);
  if (!Number.isFinite(at)) return "—";
  const d = new Date(at + 9 * 3600_000); // JST, matching the rest of the site.
  const pad = (n: number) => String(n).padStart(2, "0");
  return (
    `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())} ` +
    `${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())} JST`
  );
};
